'''
Created on Mar 20, 2012

# ---------------------------------------------------------------------------
# AccidentHotSpot.py
# Created on: 2012-06-08 11:50:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: AccidentHotSpot <Distance__value_or_field_> <VRO_Events> <VRO_mdb> 
# Description: Created by KMG
# ---------------------------------------------------------------------------

@au'''
# Import arcpy module
import arcpy

# Document variables:

mxd = arcpy.mapping.MapDocument("CURRENT")
#df = arcpy.mapping.ListDataFrames(mxd, "Layers")

# environment variables

GISWorkspace = r"C:\Workspace\AccidentAnalysis\TempAccident.mdb"  
arcpy.env.workspace = GISWorkspace
arcpy.env.overwriteOutput = True 
#arcpy.Compact_management(GISWorkspace)
print ("Workspace set to "+GISWorkspace)

# Script arguments
SlidingDistance = arcpy.GetParameterAsText(0)
if SlidingDistance == '#' or not SlidingDistance:
    SlidingDistance = "1000 Feet" # provide a default value if unspecified

Accident_Events = arcpy.GetParameterAsText(1)
if Accident_Events == '#' or not Accident_Events:
    Accident_Events = "MCL_Event" # provide a default value if unspecified

Output_PGDB = arcpy.GetParameterAsText(2)
if Output_PGDB == '#' or not Output_PGDB:
    Output_PGDB = GISWorkspace # provide a default value if unspecified

arcpy.env.workspace = Output_PGDB
print ("Workspace set to "+Output_PGDB)
 
# Local variables, text manipulation for filenames:
ScaleFactor = SlidingDistance.replace(" ","_")
ScaleFactor = ScaleFactor.replace(".","_")
AccidentBuffer = "AccidentBuffer"+ScaleFactor
Buffer1Join = "Buffer1Join"+ScaleFactor
CrashHotSpot = "CrashHotSpot"+ScaleFactor

print "will now process data to perform "+CrashHotSpot
# Process: Buffer
arcpy.Buffer_analysis(Accident_Events, AccidentBuffer, SlidingDistance, "FULL", "ROUND", "NONE", "")
print AccidentBuffer+" created in "+Output_PGDB

# Process: Spatial Join
arcpy.SpatialJoin_analysis(AccidentBuffer, Accident_Events, Buffer1Join, "JOIN_ONE_TO_ONE", "KEEP_COMMON", "", "INTERSECT", "", "")
print Buffer1Join+" created in "+Output_PGDB

# Process: Feature To Point
arcpy.FeatureToPoint_management(Buffer1Join, CrashHotSpot, "CENTROID")
print CrashHotSpot+" created in "+Output_PGDB, " process completed."

# Add the point data to the map
arcpy.MakeFeatureLayer_management(CrashHotSpot, CrashHotSpot, "#", Output_PGDB)
arcpy.RefreshActiveView()
arcpy.RefreshTOC()
