'''
Created on Jun 25, 2012

@author: kyleg
'''
# ---------------------------------------------------------------------------
# newbridge.py
# Created on: 2012-06-25 10:07:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: newbridge <Number_of_Columns> <Number_of_Rows> 
# Description: 
# ---------------------------------------------------------------------------

# Import  modules
import arcpy
#import math
#import string

#set environment variables
arcpy.env.overwriteOutput=1
ws1 = r"//GISDATA/ArcGIS/ESRI/ArcGIS10/pyWorkspace/Bridge"
ws = ws1+"/BridgeData.mdb"
mxd = r"G:\MXD\2012062501_BridgeCode.mxd"
arcpy.env.workspace = ws
Corr1 = "Corrosion"
dcorrosionval= "dCorrosionVal"

# Script arguments
bridgeID =arcpy.GetParameterAsText(0) #"test111x13"
bridge_length = arcpy.GetParameterAsText(1)  #"111"#
Bridge_Width = arcpy.GetParameterAsText(2)  #"13"#
GridSize = arcpy.GetParameterAsText(3)  #"10"#

#argument manipulation
ibridgelength = int(bridge_length)
ibridgewidth = int(Bridge_Width)
igridsize = int(GridSize)

fbridgewidth = float(Bridge_Width)
fbridgelength = float(bridge_length)

Number_of_Rows = str(ibridgewidth/igridsize)
Number_of_Columns = str(ibridgelength/igridsize)

#adjust for number of cells for remainder part, where the minimum to add a cell is 0.1 feet.  that may be adjusted

remlen = (fbridgelength/igridsize - ibridgelength/igridsize)*igridsize
remwid = (fbridgewidth/igridsize - ibridgewidth/igridsize)*igridsize

irows = int(Number_of_Rows)
icols = int(Number_of_Columns)
Number_of_Columns = Number_of_Columns+1

if remlen > 0.1: 
    icols = icols + 1
    Number_of_Columns = str(icols)
    #print "Column added for remainder "+str(remlen)+" feet"
else:
    print Number_of_Columns
    
if remwid > 0.1: 
    irows = irows + 1
    Number_of_Rows = str(irows)
    #print "row added for remainder "+str(remwid)+" feet"
else:
    print Number_of_Rows 

# Bridge Name:
newbridge = "Bridge"+bridgeID

# Process: Create Fishnet
arcpy.CreateFishnet_management(ws+"/"+newbridge, "0 0", "0 1", igridsize, igridsize, Number_of_Rows, Number_of_Columns, "#", "#", "#","POLYGON") 

#Add Field for corrosing
Intable = ws+"/"+newbridge
arcpy.AddField_management(Intable, Corr1, "LONG", 9, "", "",  "", "NULLABLE", "NON_REQUIRED", dcorrosionval)

#add results to layers
#newlayer = ws1+"/"+newbridge+".lyr"
#arcpy.SaveToLayerFile_management(newbridge, newlayer, "ABSOLUTE")
#for df in arcpy.mapping.ListDataFrames(mxd, "b*"):
#    if df.name.lower == "Bridges":
#        arcpy.mapping.AddLayer(df, newlayer, "TOP") 



