'''
Created on Mar 10, 2014

@author: kyleg
'''
#def NewRows():
import cx_Oracle
sdedev = cx_Oracle.connect('CIIMS/smiic@SDEPROD')
             
testquery = '''SELECT c1.CROSSINGID 
    from CIIMS.CIIMS_VWCROSSINGGIS3 c1 
    LEFT JOIN CIIMS.Static_Crossings s1 
        ON c1.CROSSINGID = s1.CROSSINGID 
    WHERE s1.CROSSINGID is null'''

newrows1 = '''CREATE OR REPLACE VIEW CIIMS.NEWROWS AS SELECT 
    c1.CROSSINGID, 
    c1.CROSSINGLATITUDE, 
    c1.CROSSINGLONGITUDE, 
    c1.CROSSINGTYPE 
FROM CIIMS.CIIMS_VWCROSSINGGIS3 c1 
    LEFT JOIN CIIMS.Static_Crossings s1 
    ON c1.CROSSINGID = s1.CROSSINGID 
WHERE s1.CROSSINGID IS NULL;'''

selectionex3 = '''CREATE OR REPLACE VIEW CIIMS.DELROWS AS SELECT 
    c1.CROSSINGID, 
    c1.OBJECTID 
FROM CIIMS.Static_Crossings c1 
    LEFT JOIN CIIMS.CIIMS_VWCROSSINGGIS3 s1 
    ON c1.CROSSINGID = s1.CROSSINGID 
WHERE s1.CROSSINGID IS NULL'''

delrows1 = '''CREATE OR REPLACE VIEW 
CIIMS.DELROWS AS SELECT 
    c1.CROSSINGID, 
    c1.ESRI_OID 
FROM CIIMS.Static_Crossings c1 
    LEFT JOIN CIIMS.CIIMS_VWCROSSINGGIS3 s1 
    ON c1.CROSSINGID = s1.CROSSINGID 
WHERE s1.CROSSINGID IS NULL'''

newrows = '''CREATE OR REPLACE VIEW CIIMS.NEWROWS AS
SELECT c1.CROSSINGID,
       c1.CROSSINGLATITUDE,
       c1.CROSSINGLONGITUDE,
       c1.CROSSINGTYPE
FROM CIIMS.CIIMS_VWCROSSINGGIS3 c1
       LEFT JOIN CIIMS.Static_Crossings s1 ON c1.CROSSINGID = s1.CROSSINGID
WHERE s1.CROSSINGID IS NULL;
 '''
 
delrows = '''CREATE OR REPLACE VIEW CIIMS.DELROWS AS
SELECT c1.CROSSINGID,
       c1.OBJECTID,
       c1.CROSSINGLONGITUDE,
  FROM CIIMS.Static_Crossings  c1
       LEFT JOIN CIIMS.CIIMS_VWCROSSINGGIS3 s1 ON c1.CROSSINGID = s1.CROSSINGID
 WHERE s1.CROSSINGID IS NULL;
 '''
 
cur1 = sdedev.cursor()
cur1.execute(newrows)
cur1.execute(delrows)
 