'''
Created on Sep 11, 2016

@author: kyleg
'''
from arcpy import env

def environment(prod):
    KCARS = r'Database Connections\kcarsprd_readonly.sde\KCARS.ACCIDENTS'
    NewLocation = r'Database Connections\CrashLocationProd.sde\crashlocation.SDE.Crashes_160511_gc_M92_47'
    
#Turn off background geoprocessing!!

#looka at/do 1 'year' at a  time using the Accident Key year?  Tested with 2016, not much located in KCARS.

#KCARS is crashing, cannot export anything from accident table KCARS.ACCIDENTS using ArcMap/Catalog, use FME to save KCARS table to geodatabase

#table to table, in memory, KCARS Data

#Calculate X, Y CoordinateSym

#new data is projected, so be sure to calculate the lat long Value using shape token or I calculated coordinates manually

#populate unmatched (null coordinates)  OFFICER -94.5  39.6 Decimal Degrees   KCARS_DOT -94.5  39.7 Decimal Degrees  NEW_DOT -94.4, 39.8

#Join by ACCIDENT_KEY

#create line - XY to line (features tools)

#query current year crashes INTERSECTION_TYPE IS NOT NULL AND DATE_OF_ACCIDENT BETWEEN trunc(sysdate, 'YEAR')AND add_months(trunc(sysdate, 'YEAR'), 12)-1/24/60/60

#Compare year by key ACCIDENT_KEY like '2016%'

def CompareCrashData():
    from arcpy import MakeTableView_management
    MakeTableView_management(in_table="Database Connections/kcarsprd_readonly.sde/KCARS.ACCIDENTS", out_view="ACCIDENTS_View", where_clause="ACCIDENT_KEY LIKE '2016%'", workspace="", field_info="ACCIDENT_KEY ACCIDENT_KEY VISIBLE NONE;AGENCY_ORI AGENCY_ORI VISIBLE NONE;REPORT_IMAGE_LINK REPORT_IMAGE_LINK VISIBLE NONE;LOCAL_CASE_ID LOCAL_CASE_ID VISIBLE NONE;COUNTY_NBR COUNTY_NBR VISIBLE NONE;CITY_NBR CITY_NBR VISIBLE NONE;OFFICER_MILEPOST OFFICER_MILEPOST VISIBLE NONE;ON_ROAD_KDOT_PFX_DIR ON_ROAD_KDOT_PFX_DIR VISIBLE NONE;ON_ROAD_KDOT_NAME ON_ROAD_KDOT_NAME VISIBLE NONE;ON_ROAD_KDOT_TYPE ON_ROAD_KDOT_TYPE VISIBLE NONE;ON_ROAD_KDOT_SFX_DIR ON_ROAD_KDOT_SFX_DIR VISIBLE NONE;AT_ROAD_KDOT_PFX_DIR AT_ROAD_KDOT_PFX_DIR VISIBLE NONE;AT_ROAD_KDOT_NAME AT_ROAD_KDOT_NAME VISIBLE NONE;AT_ROAD_KDOT_TYPE AT_ROAD_KDOT_TYPE VISIBLE NONE;AT_ROAD_KDOT_SFX_DIR AT_ROAD_KDOT_SFX_DIR VISIBLE NONE;AT_ROAD_KDOT_DISTANCE AT_ROAD_KDOT_DISTANCE VISIBLE NONE;AT_ROAD_KDOT_DIST_UOM AT_ROAD_KDOT_DIST_UOM VISIBLE NONE;AT_ROAD_KDOT_DIRECTION AT_ROAD_KDOT_DIRECTION VISIBLE NONE;DOT_LATITUDE DOT_LATITUDE VISIBLE NONE;DOT_LONGITUDE DOT_LONGITUDE VISIBLE NONE;NONSTATE_FUNCTION_CLASS NONSTATE_FUNCTION_CLASS VISIBLE NONE;NONSTATE_REF_POST NONSTATE_REF_POST VISIBLE NONE;BLOCK_NBR BLOCK_NBR VISIBLE NONE;ON_ROAD_SPEED_LIMIT ON_ROAD_SPEED_LIMIT VISIBLE NONE;ON_ROAD_SURFACE_TYPE ON_ROAD_SURFACE_TYPE VISIBLE NONE;ROAD_SURFTYPE_OTHER ROAD_SURFTYPE_OTHER VISIBLE NONE;ON_ROAD_SURFACE_COND ON_ROAD_SURFACE_COND VISIBLE NONE;ROAD_SURFCOND_OTHER ROAD_SURFCOND_OTHER VISIBLE NONE;ON_ROAD_SURFACE_CHAR ON_ROAD_SURFACE_CHAR VISIBLE NONE;ROAD_SURFCHAR_OTHER ROAD_SURFCHAR_OTHER VISIBLE NONE;ON_ROAD_CONST_MAINT ON_ROAD_CONST_MAINT VISIBLE NONE;ON_ROAD_NBR_OF_LANES ON_ROAD_NBR_OF_LANES VISIBLE NONE;ROAD_NBRLANES_OTHER ROAD_NBRLANES_OTHER VISIBLE NONE;AT_ROAD_SPEED_LIMIT AT_ROAD_SPEED_LIMIT VISIBLE NONE;AT_ROAD_SURFACE_TYPE AT_ROAD_SURFACE_TYPE VISIBLE NONE;AT_ROAD_SURFACE_COND AT_ROAD_SURFACE_COND VISIBLE NONE;AT_ROAD_SURFACE_CHAR AT_ROAD_SURFACE_CHAR VISIBLE NONE;AT_ROAD_CONST_MAINT AT_ROAD_CONST_MAINT VISIBLE NONE;AT_ROAD_NBR_OF_LANES AT_ROAD_NBR_OF_LANES VISIBLE NONE;DATE_OF_ACCIDENT DATE_OF_ACCIDENT VISIBLE NONE;TIME_OF_ACCIDENT TIME_OF_ACCIDENT VISIBLE NONE;DAY_OF_ACCIDENT DAY_OF_ACCIDENT VISIBLE NONE;DATE_NOTIFIED DATE_NOTIFIED VISIBLE NONE;TIME_NOTIFIED TIME_NOTIFIED VISIBLE NONE;DAY_NOTIFIED DAY_NOTIFIED VISIBLE NONE;DATE_ARRIVED DATE_ARRIVED VISIBLE NONE;TIME_ARRIVED TIME_ARRIVED VISIBLE NONE;DAY_ARRIVED DAY_ARRIVED VISIBLE NONE;ACCIDENT_CLASS_FHE ACCIDENT_CLASS_FHE VISIBLE NONE;ACCIDENT_CLASS_MHE ACCIDENT_CLASS_MHE VISIBLE NONE;ACC_CLASS_OTHER_OBJECT ACC_CLASS_OTHER_OBJECT VISIBLE NONE;COLLISION_W_OTHER_VEH_FHE COLLISION_W_OTHER_VEH_FHE VISIBLE NONE;COLLISION_W_OTHER_VEH_MHE COLLISION_W_OTHER_VEH_MHE VISIBLE NONE;COLLISION_W_VEH_OTHER COLLISION_W_VEH_OTHER VISIBLE NONE;FIXED_OBJECT_TYPE_FHE FIXED_OBJECT_TYPE_FHE VISIBLE NONE;FIXED_OBJECT_TYPE_MHE FIXED_OBJECT_TYPE_MHE VISIBLE NONE;FIXED_OBJECT_OTHER FIXED_OBJECT_OTHER VISIBLE NONE;ACCIDENT_LOCATION ACCIDENT_LOCATION VISIBLE NONE;ACCIDENT_LOCATION_OTHER ACCIDENT_LOCATION_OTHER VISIBLE NONE;INTERSECTION_TYPE INTERSECTION_TYPE VISIBLE NONE;ROUNDABOUT_NBR ROUNDABOUT_NBR VISIBLE NONE;LIGHT_CONDITIONS LIGHT_CONDITIONS VISIBLE NONE;WEATHER_CONDITIONS WEATHER_CONDITIONS VISIBLE NONE;WEATHER_COND_OTHER WEATHER_COND_OTHER VISIBLE NONE;ANIMAL_TYPE ANIMAL_TYPE VISIBLE NONE;KDOT_WORK_ZONE_FLAG KDOT_WORK_ZONE_FLAG VISIBLE NONE;WORK_ZONE_LOCATION WORK_ZONE_LOCATION VISIBLE NONE;WORK_ZONE_CATEGORY WORK_ZONE_CATEGORY VISIBLE NONE;WORK_ZONE_CAT_OTHER WORK_ZONE_CAT_OTHER VISIBLE NONE;OBJECT_DAMAGED1 OBJECT_DAMAGED1 VISIBLE NONE;KDOT_PROP_DAMAGE_FLAG1 KDOT_PROP_DAMAGE_FLAG1 VISIBLE NONE;OBJECT_DAMAGED2 OBJECT_DAMAGED2 VISIBLE NONE;KDOT_PROP_DAMAGE_FLAG2 KDOT_PROP_DAMAGE_FLAG2 VISIBLE NONE;SPECIAL_EVENT SPECIAL_EVENT VISIBLE NONE;SPECIAL_DATA SPECIAL_DATA VISIBLE NONE;SPECIAL_JURISDICTION SPECIAL_JURISDICTION VISIBLE NONE;SPECIAL_JURIS_OTHER SPECIAL_JURIS_OTHER VISIBLE NONE;ON_ROAD_PREFIX_DIRECTION ON_ROAD_PREFIX_DIRECTION VISIBLE NONE;ON_ROAD_NAME ON_ROAD_NAME VISIBLE NONE;ON_ROAD_TYPE ON_ROAD_TYPE VISIBLE NONE;ON_ROAD_SUFFIX_DIRECTION ON_ROAD_SUFFIX_DIRECTION VISIBLE NONE;ON_ROAD_ALTERNATE_NAME ON_ROAD_ALTERNATE_NAME VISIBLE NONE;AT_ROAD_PREFIX_DIRECTION AT_ROAD_PREFIX_DIRECTION VISIBLE NONE;AT_ROAD_NAME AT_ROAD_NAME VISIBLE NONE;AT_ROAD_TYPE AT_ROAD_TYPE VISIBLE NONE;AT_ROAD_SUFFIX_DIRECTION AT_ROAD_SUFFIX_DIRECTION VISIBLE NONE;AT_ROAD_DISTANCE AT_ROAD_DISTANCE VISIBLE NONE;AT_ROAD_DISTANCE_UOM AT_ROAD_DISTANCE_UOM VISIBLE NONE;AT_ROAD_DIRECTION AT_ROAD_DIRECTION VISIBLE NONE;LATITUDE LATITUDE VISIBLE NONE;LONGITUDE LONGITUDE VISIBLE NONE;S_REF_DISTANCE S_REF_DISTANCE VISIBLE NONE;S_REF_ROAD S_REF_ROAD VISIBLE NONE;W_REF_DISTANCE W_REF_DISTANCE VISIBLE NONE;W_REF_ROAD W_REF_ROAD VISIBLE NONE;OFFICER OFFICER VISIBLE NONE;OFFICER_BADGE_ID OFFICER_BADGE_ID VISIBLE NONE;REPORTING_SEVERITY REPORTING_SEVERITY VISIBLE NONE;AMENDED_REPORT_FLAG AMENDED_REPORT_FLAG VISIBLE NONE;DUI_FLAG DUI_FLAG VISIBLE NONE;PRIVATE_PROPERTY_FLAG PRIVATE_PROPERTY_FLAG VISIBLE NONE;REPORT_BATCH_ID REPORT_BATCH_ID VISIBLE NONE;CODER CODER VISIBLE NONE;CASE_STATUS CASE_STATUS VISIBLE NONE;DATA_VERSION_YEAR DATA_VERSION_YEAR VISIBLE NONE;DATA_SOURCE DATA_SOURCE VISIBLE NONE;KDOT_UPDATE_TMSTMP KDOT_UPDATE_TMSTMP VISIBLE NONE;USER_ID USER_ID VISIBLE NONE;CREATED_DATE CREATED_DATE VISIBLE NONE;CREATED_BY CREATED_BY VISIBLE NONE;MODIFIED_DATE MODIFIED_DATE VISIBLE NONE;MODIFIED_BY MODIFIED_BY VISIBLE NONE;UAB UAB VISIBLE NONE;COUNTY_REF_POST_TMP COUNTY_REF_POST_TMP VISIBLE NONE;LANE_DIRECTION_TMP LANE_DIRECTION_TMP VISIBLE NONE;ESRI_OID ESRI_OID VISIBLE NONE")




    
    